version: '2.1'

services:
  neo4j:
    image: neo4j
    volumes:
      - ./neo4j/data:/data
    ports:
      - 7474:7474
      - 7687:7687

  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - ..:/home/jovyan/work
    ports:
      - 8888:8888
